project:
  type: website
  output-dir: docs

website:
  title: "Lance Nemecek"
  navbar:
    left:
      - file: index.qmd
        text: Home
      - file: about.qmd
        text: Courses
      - file: Projectsland.qmd
        text: Projects
      - text: Maps
        menu: 
          - us_states.qmd
          - wisconsin_districts.qmd
      - file: BirthdayParadox.qmd
        text: The Birthday Paradox

page-footer:
    left: |
      &copy; Lance Nemecek, 2024<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

